apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yaml-herder
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/part-of: yaml-herder
